@root= http://localhost:8000/

###
@user= {{root}}api/v1/user

GET {{root}}

####
POST {{user}}
Content-Type: application/json


    {
        "role":"admin",
        "fName":"hdsab",
        "lName":"djisaj",
        "email":"1234asndia@gmail.com",
        "password":"213sad"
    }
###
GET {{user}}
Content-Type: application/json

{
    "email":"1234@gmail.com",
    "password":"123"
}

###
POST {{root}}api/v1/category
Content-Type: application/json

{
    "title":"Home Goods"
}
###
GET {{root}}api/v1/category
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhYmFiYWJAZ21haWwuY29tIiwiaWF0IjoxNjkwNjc5MTMxLCJleHAiOjE2OTA2Nzk3MzF9.OI7A9GbzmrT8KTeP9PFcNbq7ijXQ7YFjWPBW8PimOeg

